<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<NuGetPackages>$(UserProfile)\.nuget\packages</NuGetPackages>
		<JotunnProps>$(NuGetPackages)\jotunnlib\2.30.0\build\JotunnLib.props</JotunnProps>
	</PropertyGroup>

	<Import Project="environment.props" Condition="Exists('environment.props')" />
	<Import Project="$(JotunnProps)" Condition="Exists('$(JotunnProps)')" />

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>10.0</LangVersion>
		<AssemblyName>SNEAKer</AssemblyName>
		<RootNamespace>SNEAKer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="JotunnLib" Version="2.30.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="assembly_valheim">
			<HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_valheim_publicized.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
		</Reference>
		<Reference Include="assembly_utils">
			<HintPath>$(VALHEIM_MANAGED)/publicized_assemblies/assembly_utils_publicized.dll</HintPath>
			<SpecificVersion>False</SpecificVersion>
		</Reference>
	</ItemGroup>
</Project>
